---
# tasks file for docker_install
- name: Update all packages
  yum:
     name: '*'
     state: latest
     update_only: yes

- name: Ensure a list of yum packages are installed
  yum: 
     name: "{{ packages }}"
     state: latest
     update_cache: yes
  vars:
     packages:
         - amazon-linux-extras
         - python-pip
         - yum-utils
         - device-mapper-persistent-data
         - lvm2
        
- name: Add extras repository
  shell: yum-config-manager --enable extras

- name: Enable Some packages from amazon-linux-extras packages
  shell: "amazon-linux-extras enable docker ansible2 python3.8"

- name: Clean yum metadata cache
  command: yum clean metadata
  args:
     warn: false

 
- name: Install docker-ce (centos) via amazon-linux-extras packages
  shell: "amazon-linux-extras install docker -y"
 
- name: Ensure a list of packages are installed
  yum:
     name: "{{ packages }}"
     state: latest
     update_cache: yes
  vars:
      packages:
      - python3.8
      - ansible
      - docker

- name: Enable Docker CE service at startup
  service:
     name: docker
     state: started
     enabled: yes

- name: Upgrade pip3
  shell: "python3.8 -m pip install pip --upgrade"

- name: Ensure Python pip packages are installed
  pip:
     name: "{{ packages }}"
     executable: /usr/local/bin/pip3.8
  vars:
     packages:
          - boto
          - boto3
          - docker-compose
 
- name: Add ec2-user to docker group
  user: 
     name: ec2-user
     append: yes
     groups: docker
  become: true
