pipeline {

    agent {
        label 'build_server'
    }


    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven 'M3'
        jdk 'jdk8'
    }

    stages {

        stage('Clone Repository') {
        // Get some code from a GitHub repository
            steps {
                git branch: 'main', credentialsId: 'da74d16f-289d-4d8b-9a60-b9a41ac207ce', url: 'git@github.com:auke-n/pet-clinic.git'
            }
        }
        stage('Build artifact') {
            steps {
                dir('app-src') {
                    echo '=== Building Petclinic Application ==='
                    sh 'mvn package'
                }
            }
        }

        stage('Build Docker Image') {

            steps {
                echo '=== Building Petclinic Docker Image ==='
                dir('app-src') {
                    sh 'sudo docker build . -t gerbut/pet-clinic:1.${BUILD_NUMBER} -t gerbut/pet-clinic:latest'
                }
            }
        }

        stage('Test Image') {

        agent {
             label 'QA'
            }

            steps {
                echo '=== Run smoke test on QA_server ==='
                dir('/var/lib/jenkins/workspace/petclinic/iac/config/tests') {
                sh 'chmod +x test_smoke.sh'
                sh './test_smoke.sh'
                }

                echo '=== Run regression tests on QA_server ==='
                dir('/var/lib/jenkins/workspace/petclinic/iac/config/tests') {
                sh 'chmod +x test_regression.sh'
                sh './test_regression.sh'
                }
            }
        }

        stage('Push Image to Docker Registry') {

        agent {
                label 'build_server'
            }

            steps {
                echo '=== Push Image to Docker Registry ==='

               withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh 'docker logout'
                    sh "sudo docker login -u ${USERNAME} -p ${PASSWORD}"
                    sh "sudo docker push docker.io/gerbut/pet-clinic:1.${BUILD_NUMBER}"
                    sh "sudo docker push docker.io/gerbut/pet-clinic:latest"
                }
            }
        }

        stage('Remove Docker Images from the build_server') {
           steps {
                echo '=== Remove docker images from the build_server ==='
                sh "sudo docker image prune -a -f"
            }
        }

        stage('Deploy to Production') {

        agent {
                label 'Master'
            }

            steps {
                echo '=== Run application on production-server ==='

                sh 'ssh -i ~/.ssh/jenkins.prv -o StrictHostKeyChecking=no ec2-user@web.server "sudo docker rm -f web;"'
                sh 'ssh -i ~/.ssh/jenkins.prv -o StrictHostKeyChecking=no ec2-user@web.server "sudo docker run -d --name web -p 80:8080 gerbut/pet-clinic:latest;"'
            }
        }
    }
}