---
- hosts: root-server
  become: true
  roles:
      - role: git_install
      - role: java_install
      - role: jenkins_install


- hosts: build-server
  become: true
  roles:
      - role: docker_install


- hosts: build-server
  become: true
  roles:
      - role: docker_install

- hosts: web-server
  become: true
  roles:
      - role: docker_install


