---
- hosts: localhost
  become: true
  roles:
      - role: java_install
      - role: jenkins_install

- hosts: build-server
  become: true
  roles:
      - role: docker_install

- hosts: test-server
  become: true
  roles:
      - role: docker_install

- hosts: web-server
  become: true
  roles:
      - role: docker_install


